platform.name: 'binance'

event:
  broker-url: 'tcp://localhost:61616'
  topic:
    platform: 'platform-update'

org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
spring.quartz.job-store-type: memory
